# Generated by Django 5.2.7 on 2025-10-18 10:43

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('unique_ID', models.PositiveIntegerField(default=False, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('checkbox', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to=student.models.student_directory_name)),
            ],
        ),
    ]
