# Generated by Django 5.2.7 on 2025-10-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_ID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
